### ISSUE TITLE
inspec-azure + docker (can't convert nil into Integer)

### ISSUE THREAD

**Issue by marcomancuso** [inspec/inspec-azure#109]
### 🎛 Description

🐛 bug report

chef/inspec:latest docker image should work with Azure Inspec

### 🌍 InSpec and Platform Version

inspec 2.2.50
MacOS 10.13.6
Docker Version 18.03.1-ce-mac65 (24312)
chef/inspec:latest

### 🤔 Replication Case

- create a new inspec project with `inspec init`
- add environment variables for AZURE credentials
- create simple control:
```
control 'Check VM properties' do
  describe azurerm_virtual_machine(resource_group: rg_name, name: vm_name) do
    it                                { should exist }
    it                                { should_not have_endpoint_protection_installed([]) }
    its('type')                       { should eq 'Microsoft.Compute/virtualMachines' }
    its('location')                   { should eq 'westeurope' }
    its('data_disk_names')            { should eq [] }
  end
end
```
- edit inspec.yml
```
name: azure-create-virtualmachine
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '>= 2.2.7'
depends:
  - name: inspec-azure
    git: https://github.com/inspec/inspec-azure.git
supports:
  - platform: azure
```
- from the inspec profile folder run 
`docker run -it -e AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID} -e AZURE_CLIENT_ID=${AZURE_CLIENT_ID} -e AZURE_TENANT_ID=${AZURE_TENANT_ID} -e AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} — rm -v $(pwd):/share chef/inspec:latest  exec .  -t azure://`

result:

fails with:
`libraries/support/azure/authentication.rb:41:in `Integer': can't convert nil into Integer (TypeError)`

But if I get into the docker container overriding the entrypoint with
`docker run --entrypoint /bin/sh -it -e AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID} -e AZURE_CLIENT_ID=${AZURE_CLIENT_ID} -e AZURE_TENANT_ID=${AZURE_TENANT_ID} -e AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} -v $(pwd):/share chef/inspec:latest`

and inside run `inspec  exec .  -t azure://` then it works fine

### 💁 Possible Solutions

N/A

### 💻 Stacktrace
```
Traceback (most recent call last):
	43: from /usr/local/bundle/bin/inspec:23:in `<main>'
	42: from /usr/local/bundle/bin/inspec:23:in `load'
	41: from /usr/local/bundle/gems/inspec-2.2.50/bin/inspec:12:in `<top (required)>'
	40: from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	39: from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	38: from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	37: from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	36: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/cli.rb:171:in `exec'
	35: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/runner.rb:103:in `run'
	34: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/runner.rb:82:in `load'
	33: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/runner.rb:82:in `each'
	32: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/runner.rb:93:in `block in load'
	31: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/profile.rb:168:in `collect_tests'
	30: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/profile.rb:168:in `each'
	29: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/profile.rb:171:in `block in collect_tests'
	28: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/profile_context.rb:142:in `load_control_file'
	27: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/profile_context.rb:158:in `load_with_context'
	26: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/profile_context.rb:158:in `instance_eval'
	25: from ./controls/example.rb:9:in `load_with_context'
	24: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/resource.rb:51:in `block (3 levels) in create_dsl'
	23: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/resource.rb:51:in `new'
	22: from /usr/local/bundle/gems/inspec-2.2.50/lib/inspec/plugins/resource.rb:68:in `initialize'
	21: from libraries/azurerm_virtual_machine.rb:28:in `initialize'
	20: from libraries/support/azure/management.rb:102:in `virtual_machine'
	19: from libraries/support/azure/service.rb:58:in `get'
	18: from libraries/support/azure/service.rb:11:in `fetch'
	17: from libraries/support/azure/service.rb:11:in `fetch'
	16: from libraries/support/azure/service.rb:11:in `block in fetch'
	15: from libraries/support/azure/service.rb:59:in `block in get'
	14: from libraries/support/azure/rest.rb:17:in `get'
	13: from /usr/local/bundle/gems/faraday-0.15.2/lib/faraday/connection.rb:138:in `get'
	12: from /usr/local/bundle/gems/faraday-0.15.2/lib/faraday/connection.rb:379:in `run_request'
	11: from /usr/local/bundle/gems/faraday-0.15.2/lib/faraday/connection.rb:394:in `build_request'
	10: from /usr/local/bundle/gems/faraday-0.15.2/lib/faraday/request.rb:25:in `create'
	 9: from /usr/local/bundle/gems/faraday-0.15.2/lib/faraday/request.rb:25:in `tap'
	 8: from /usr/local/bundle/gems/faraday-0.15.2/lib/faraday/request.rb:26:in `block in create'
	 7: from /usr/local/bundle/gems/faraday-0.15.2/lib/faraday/connection.rb:398:in `block in build_request'
	 6: from /usr/local/bundle/gems/faraday-0.15.2/lib/faraday/connection.rb:384:in `block in run_request'
	 5: from /usr/local/bundle/gems/faraday-0.15.2/lib/faraday/connection.rb:140:in `block in get'
	 4: from libraries/support/azure/rest.rb:21:in `block in get'
	 3: from libraries/support/azure/rest.rb:44:in `authorization_header'
	 2: from libraries/support/azure/authentication.rb:19:in `authentication_header'
	 1: from libraries/support/azure/authentication.rb:41:in `acquire_token'
libraries/support/azure/authentication.rb:41:in `Integer': can't convert nil into Integer (TypeError)
````

**Comment by dmccown** [comment]
Thank you for reporting your issue. This resource pack should work with InSpec shipped within docker. Can you double check the syntax you reported:

```
docker run -it -e AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID} -e AZURE_CLIENT_ID=${AZURE_CLIENT_ID} -e AZURE_TENANT_ID=${AZURE_TENANT_ID} -e AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} — rm -v $(pwd):/share chef/inspec:latest exec . -t azure://
```

It looks like there's no space between ` -e AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} ` and `--rm`. It also looks like your `rm` has an em dash instead of two dashes. Once I corrected that I was able to run my scan with:

```
docker run -it -e AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID} -e AZURE_CLIENT_ID=${AZURE_CLIENT_ID} -e AZURE_TENANT_ID=${AZURE_TENANT_ID} -e AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} --rm -v $(pwd):/share chef/inspec:latest exec . -t azure://
```
Give that a shot and let us know if you are still having issues.

**Comment by marcomancuso** [comment]
@dmccown my bad, yes that was a missing dash, it works now, thanks!

**Comment by dmccown** [comment]
@marcomancuso Did you find erroneous documentation that led to you forgetting the dash? I just wanted to make sure we don't have an error in documentation we need to correct. 

Thanks!

**Comment by marcomancuso** [comment]
@dmccown, no I think I took it from https://medium.com/@g.sowinski/introduction-to-inspec-for-azure-d4ea1316c23b, there is one long dash instead of 2 normal dashes and when copied to the shell it's a single dash. I can see in the official Inspec docs is well formatted with 2 dashes
