### ISSUE TITLE
InSpec states 'Client id cannot be nil' on MSI Enabled VM

### ISSUE THREAD

**Issue by rdtechie** [inspec/inspec-azure#163]
### 🎛 Description

🐛

I've enabled MSI on a VM that I have running in my subscription, and it appears that InSpec cannot make use of the MSI functionality. I exported my tenant ID as environment variable AZURE_TENANT_ID. When running a test InSpec reports:
`Client id cannot be nil`

### 🌍 InSpec and Platform Version

```
inspec --version
3.4.1

hostnamectl
(some output is omitted)
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-862.11.6.el7.x86_64
Architecture: x86-64
```

### 🤔 Replication Case
* Enabled MSI on VM through the Azure Portal.
* Added owner role to MSI

Created new InSpec profile with: `inspec init profile azure`

Directory structure of directory azure:
```
├── controls
│   └── resource_group.rb
├── inspec.yml
├── libraries
└── README.md
```

Contents of ~/azure/inspec.yml
```
name: profile-azure
title: Azure Example Profile
maintainer: Chef Software, Inc.
copyright: Chef Software, Inc.
copyright_email: support@chef.io
license: Apache-2.0
summary: Demonstrates the use of an InSpec Compliance Profile on Azure
version: 1.0.0
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
supports:
  - platform: azure
```
Contents of controls/resource_group.rb
```
control 'azure_resource_group_example' do
    title 'Check if the Example Resource Group matches expectations'
    impact 1.0

    describe azure_resource_group(name: 'WeEu-S03-Dev-Rsg-Mlce-01') do
      # Check if the Resource Group is located in the correct region
      its('location') { should cmp 'westeurope' }

      # Check if the Resource Group has tags
      it { should have_tags }
    end
  end
```

### 💁 Possible Solutions

n/a

### 💻 Stacktrace
I've exported my subscription ID to the environment variable AZURE_SUBSCRIPTION_ID and ran the following command:
`inspec shell -t azure:// --diagnose'

I got the following output:
```
InSpec version: 3.4.1
Train version: 1.7.1
Command line configuration:
{"winrm_transport"=>"negotiate",
 "insecure"=>false,
 "depends"=>[],
 "distinct_exit"=>true,
 "target"=>"azure://<removed manually by me for sake of privacy>",
 "diagnose"=>true}
JSON configuration file:
{}
Merged configuration:
{"reporter"=>{"cli"=>{"stdout"=>true}},
 "type"=>:shell,
 "winrm_transport"=>"negotiate",
 "insecure"=>false,
 "depends"=>[],
 "distinct_exit"=>true,
 "target"=>"azure://<removed manually by me for sake of privacy>",
 "diagnose"=>true}

Traceback (most recent call last):
        17: from /bin/inspec:122:in `<main>'
        16: from /bin/inspec:122:in `load'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/bin/inspec:12:in `<top (required)>'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/cli.rb:307:in `shell_func'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/cli.rb:307:in `new'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:58:in `initialize'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:66:in `configure_transport'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/backend.rb:51:in `create'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.1/lib/train/transports/azure.rb:27:in `connection'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.1/lib/train/transports/azure.rb:27:in `new'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.1/lib/train/transports/azure.rb:57:in `initialize'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.1/lib/train/transports/azure.rb:91:in `connect'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.1/lib/train/transports/azure.rb:91:in `new'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/ms_rest_azure-0.11.0/lib/ms_rest_azure/credentials/application_token_provider.rb:51:in `initialize': Client id cannot be nil (ArgumentError)
```

**Comment by r-fennell** [comment]
Hi @rdtechie - thank you for this.
I will triage the issue and aim to get back to you in a timely manner.
Ruairi

**Comment by rdtechie** [comment]
Hi @r-fennell, did you managed to replicate the issue, or have a update on this for me?

**Comment by rdtechie** [comment]
Hello @r-fennell , do you have an update for me?

**Comment by r-fennell** [comment]
Hi @rdtechie - I haven't yet had time to look into this. I will prioritize it and have an update for you this week.
Thanks again,
Ruairi

**Comment by rdtechie** [comment]
Hi @r-fennell , we're 6 weeks later now after your last comment; is this issue resolved?

**Comment by rdtechie** [comment]
As much as I would like to use InSpec, this issue is a blocker. And the additional fact that there is not much interaction from Chef here, I decided to go for the Pester route to do infrastructure testing.

**Comment by cgordoncarroll** [comment]
Has anyone found a definitive answer to this?
