### ISSUE TITLE
NoMethodError on version 4.17.x of InSpec

### ISSUE THREAD

**Issue by eugeneromero** [inspec/inspec-azure#201]
# Describe the problem
When using inspec-azure (tested latest version, 1.3.6) along with InSpec versions 4.17.x (tested from 4.17.6 to 4.17.15), running `inspec check` results in an error.

# Steps to reproduce
- Install inspec v 4.17.x
- Init a project (`inspec vendor --overwrite`) with the following in `inspec.yml`:
```
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
supports:
  - platform: azure
```
- Run `inspec check` on the tests folder (can be empty)

## Expected result:
No errors reported.

## Actual result:
```
$ inspec check test/integration/
Traceback (most recent call last):
	30: from /usr/bin/inspec:185:in `<main>'
	29: from /usr/bin/inspec:185:in `load'
	28: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.17.15/bin/inspec:11:in `<top (required)>'
	27: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/base_cli.rb:33:in `start'
	26: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	25: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	24: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	23: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	22: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/cli.rb:117:in `check'
	21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:421:in `check'
	20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:451:in `controls_count'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:195:in `params'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:597:in `load_params'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:603:in `load_checks_params'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:247:in `load_libraries'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:247:in `each_with_index'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:247:in `each'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:262:in `block in load_libraries'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile.rb:270:in `load_libraries'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile_context.rb:134:in `load_libraries'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile_context.rb:134:in `each'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile_context.rb:137:in `block in load_libraries'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile_context.rb:150:in `load_library_file'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile_context.rb:161:in `load_with_context'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/profile_context.rb:161:in `instance_eval'
	 5: from libraries/azurerm_ad_user.rb:3:in `load_with_context'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/dsl_shared.rb:26:in `require'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/dsl_shared.rb:26:in `eval'
	 2: from libraries/azurerm_resource.rb:5:in `create'
	 1: from libraries/azurerm_resource.rb:6:in `<class:AzurermResource>'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.15/lib/inspec/plugin/v1/plugin_types/resource.rb:34:in `supports': undefined method `to_sym' for nil:NilClass (NoMethodError)
```

## Possible Solution
My guess is this has something to do with the changes made in [this pull request](https://github.com/inspec/inspec/commit/3b69967cc8365a43f45737e4390a7a3ae97c1024#diff-97cbc2a879b4ce388a6c777552c2b542). In line 34 InSpec is expecting a `name` value it can convert to a symbol, but this value is not being passed by inspec-azure.

**Comment by zenspider** [comment]
Part of the problem at the very least is the config that points to `https://github.com/inspec/inspec-azure/archive/master.tar.gz`... this means it'll pick up whatever is on head at the time it downloads. Please change that line to be a version tag that corresponds to inspec 4.17.6 (basically by date).

**Comment by eugeneromero** [comment]
I agree that having a floating version is not good practice, especially for production. While an acceptable workaround, the actual issue still remains. But in the meantime it is of course a good idea to pin the inspec-azure version.

**Comment by rmoles** [comment]
Hi @eugeneromero, I just wanted to check with you whether you are still experiencing this issue?

**Comment by eugeneromero** [comment]
Hey @rmoles, I just checked with the latest versions (inspec 4.18.51, inspec-azure 1.10.0) and the issue is indeed solved. Thank you everyone for your work on this! Closing issue.

**Comment by rohancollab** [comment]
Hello @eugeneromero , I got a similar issue. I have inspec version 4.22.0 and I am wanting to run tests against my azure webapp in a debian host. 

I tried changing the inspec azure resource pack to include a version as follows
```yaml
name: azure-profile
title: My own Azure profile
version: 1.0.0
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/v1.18.1.tar.gz
```
However it still fails with 
```

 inspec exec "Inspec-AzureTests"
/usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/profile.rb:270:in `block in load_libraries': undefined method `[]=' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/profile.rb:263:in `each'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/profile.rb:263:in `each_with_index'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/profile.rb:263:in `load_libraries'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/runner.rb:107:in `block in load'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/runner.rb:101:in `each'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/runner.rb:101:in `load'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/runner.rb:135:in `run'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/cli.rb:279:in `exec'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/inspec-core-4.22.0/lib/inspec/base_cli.rb:35:in `start'
	from /usr/local/bundle/gems/inspec-bin-4.22.0/bin/inspec:11:in `<top (required)>'
	from /usr/local/bundle/bin/inspec:23:in `load'
	from /usr/local/bundle/bin/inspec:23:in `<main>'
ERROR: Job failed: exit code 1
```

I am not sure which inspec-azure version  is correct for my inspec-version ie 4.22.0

**Comment by eugeneromero** [comment]
Hi @rohancollab, I think your issue is different from the one I was experiencing. I recommend you open a new issue so it gets the visibility you need, as people won't look at comments on this one since its closed.
Best of luck!

**Comment by rohancollab** [comment]
Yep, that's right. Better open a new issue then. Thanks @eugeneromero
