### ISSUE TITLE
I want to test new feature branch

### ISSUE THREAD

**Issue by omerdemirok** [inspec/inspec-azure#281]
> Thanks for this excellent catch, @NathanPrado. Fixing this unearthed some other issues as well.
> There are some new dependencies that need to be added to the train plug-in. [see](https://github.com/inspec/train/pull/629)
> Until then, you can clone this branch and test it locally.
> Please check project [readme](https://github.com/omerdemirok/inspec-azure) and example [inspec.yml](https://github.com/inspec/inspec-azure/blob/azure_generic_resources/test/integration/verify/inspec.yml).

I really appreciate your effort, thank for looking into that.  Glad to kill off more bugs.  I tried pulling down the latest of this branch locally and referencing it in my tests but got this error now

```
1: from C:/opscode/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/opscode/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- facets/string (LoadError)|
```

Am I missing a step?  Please let me know what I can do to help!

_Originally posted by @NathanPrado in https://github.com/inspec/inspec-azure/pull/277#issuecomment-671537546_

**Comment by omerdemirok** [comment]
@NathanPrado
In case you might have follow up questions, it is better to move it out from the PR review thread.

Steps to test a new branch locally:
- `git clone https://github.com/inspec/inspec-azure.git`
- `cd inspec-azure`
- `git checkout <branch_name>` e.g. `azure_generic_resources`
- Ensure that environment variables are set: https://github.com/inspec/inspec-azure/tree/azure_generic_resources#service-principal
- `bundle install`
- `bundle exec inspec exec <my_profile> -t azure://`

!! IMPORTANT !!
- Delete the old `inspec.lock` in  `<my_profile>` if exists.
- Update the `inspec.yml` to point the local resources:
```depends:
  - name: this-depend-loads-resources
    path: /path/to/local/inspec-azure
supports:
  - platform: azure
```
- This resources should be used for testing purposes only until it is merged to the master branch.
